### ISSUE TITLE
Problems training - Implementing VAE Code - 11

### ISSUE THREAD

**Issue by ghost** [musikalkemist/generating-sound-with-neural-networks#1]
Hello Valerio! Hope all is well.

I have a problem regarding video 11 where you change the encoder after making a vanilla distinction. In this repository I can't run the train.py code (the main one, where we instantiate the VAE works, and prints the summary) giving me the following error:

__________________________
Traceback (most recent call last):
  File "/home/luis/Desktop/vae-tensorflow/train.py", line 38, in <module>
    autoencoder = train(x_train[:10000], LEARNING_RATE, BATCH_SIZE, EPOCHS)
  File "/home/luis/Desktop/vae-tensorflow/train.py", line 31, in train
    autoencoder.compile(learning_rate)
  File "/home/luis/Desktop/vae-tensorflow/autoencoder.py", line 53, in compile
    self.model.compile(optimizer=optimizer,
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 444, in compile
    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1800, in _cache_output_metric_attributes
    self._per_output_metrics = training_utils_v1.collect_per_output_metric_info(
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_utils_v1.py", line 910, in collect_per_output_metric_info
    metric_fn._from_serialized = from_serialized  # pylint: disable=protected-access
AttributeError: 'method' object has no attribute '_from_serialized'
__________________________

Running TF 2.5, CUDA 11.2 on ubuntu with NVIDIA 460.80
Thank you

**Comment by Leofltt** [comment]
Hi @luisArandas you need to run the version of tensorflow from the requirements.txt, which is 2.3.1

**Comment by jenschne** [comment]
Hi, very helpful code. I have the same issue, though. Is there a fix other than downgrading tensorflow to run this?

**Comment by Leofltt** [comment]
> Hi, very helpful code. I have the same issue, though. Is there a fix other than downgrading tensorflow to run this?

I highly doubt so. It's best practice when working with python to use sandboxed environments such as virtualenv, conda or Docker exactly because of this issue with dependencies. If the requirements file explicitly expresses this version of tensorflow as the one to use it's because other versions are likely to break compatibility. I would recommend you create a virtual environment to run this project in and install there the appropriate version of tensorflow

**Comment by jenschne** [comment]
I used docker etc. to get this example going, but the custom loss in VAEs makes this a particular hacky example (turning off eager evaluation, downgrading to older versions, etc.) Keras/TF does not seem overly friendly to implementing the bottleneck layer... Anyway, FYI: the code also runs with TF 2.4.0 and Keras 2.4.0.

**Comment by Ebtesam123** [comment]
I have installed the specified tensorflow version 2.3.1 using conda venv. But the same error appears when training VAE. Any help Please?!

**Comment by yogeshjangra** [comment]
I am using tensorfow 2.6.0, 
I removed the metric parameter in the compile function and the error is resolved. 
Below is the snippet of my compile function:
    def compile(self, learning_rate = 0.0001):
        optimizer = Adam(learning_rate=learning_rate)
        self.model.compile(optimizer=optimizer, loss= self._calculate_combined_loss)
