### ISSUE TITLE
ValueError with code 13

### ISSUE THREAD

**Issue by Martyn0324** [musikalkemist/generating-sound-with-neural-networks#2]
I did a copy+paste of the [train.py](https://github.com/musikalkemist/generating-sound-with-neural-networks/blob/main/13%20Training%20VAE%20with%20audio%20data/train.py ) code, changed the name of the function **load_fsdd** to **load_dataset** and tried to use a dataset I've created using a character's voice lines from a game.

However, I'm getting the following error:

```
Traceback (most recent call last):

  File "D:\Python\generate.py", line 8, in <module>
    from Audio_GAN2 import VAE

  File "D:\Python\Audio_GAN2.py", line 317, in <module>
    X_train, _, _, _ = load_dataset('D:/Python/GAN/spectrogram')

ValueError: too many values to unpack (expected 4)
```

The "spectrogram" file has 149 .wav.npy items.

**Here's the code:**

```
def load_dataset(spectrograms_path):
    x_train = []
    for root, _, file_names in os.walk(spectrograms_path):
        for file_name in file_names:
            file_path = os.path.join(root, file_name)
            spectrogram = np.load(file_path) # (n_bins, n_frames, 1)
            x_train.append(spectrogram)
    x_train = np.array(x_train)
    x_train = x_train[..., np.newaxis] # -> (3000, 256, 64, 1)
    return x_train
```

Can someone give me a hint on how to solve this?

**Comment by Martyn0324** [comment]
I think I got it now.
In SPECTROGRAMS_PATH, I've forgot to add a "/" at the end of the string, so it got like: `"C:/Users/Python/spectrograms"` instead of `"C:/Users/Python/spectrograms/"`
